data "grafana-dashboard-json_row" "row_a" {
  // See the docs for grafana-dashboard-json_row
}
data "grafana-dashboard-json_panel" "panel_a" {
  // See the docs for grafana-dashboard-json_panel
}
data "grafana-dashboard-json_panel" "panel_b" {
  // See the docs for grafana-dashboard-json_panel
}

data "grafana-dashboard-json_dashboard" "example" {
  title       = "Example dashboard"
  description = "This is an example dashboard which is generated by Terraform."
  tags        = ["managed-by-terraform"]

  time {
    from = "now-6h"
    to   = "now"
  }

  timepicker {
    time_options      = ["5m", "15m", "1h"]
    refresh_intervals = ["15s", "1m", "5m", "15m", "30m", "1h"]
  }

  panels = [
    data.grafana-dashboard-json_row.row_a.rendered_json,
    data.grafana-dashboard-json_panel.panel_a.rendered_json,
    data.grafana-dashboard-json_panel.panel_b.rendered_json,
  ]
}

resource "grafana_dashboard" "example" {
  config_json = data.grafana-dashboard-json_dashboard.example.rendered_json
}
