data "grafana-dashboard-json_dashboard" "example" {
  title       = "Example dashboard"
  description = "This is an example dashboard which is generated by Terraform."
  tags        = ["managed-by-terraform"]

  time {
    from = "now-6h"
    to   = "now"
  }

  timepicker {
    time_options      = ["5m", "15m", "1h"]
    refresh_intervals = ["15s", "1m", "5m", "15m", "30m", "1h"]
  }

  panels = []
  extra_panel_json = jsonencode([
    {
      type      = "row"
      title     = "Example Row"
      titleSize = "h6"
      gridPos = {
        h = 1
        w = 24
        x = 0
        y = 0
      }
    },
    // Other panels can go here
  ])
}

resource "grafana_dashboard" "example" {
  config_json = data.grafana-dashboard-json_dashboard.example.rendered_json
}
